"editor.line_nr" = { fg = "surface1", bg = "base" }
"editor.current_line_nr" = { fg = "text", bg = "base" }
"editor.text" = { fg = "text" }
"editor.dim_text" = { fg = "surface0" }
"editor.info_line" = { fg = "subtext1", bg = "mantle" }
"editor.info_line.unfocused" = { fg = "surface1", bg = "mantle" }
"editor.background" = { fg = "text", bg = "base" }
"editor.selection" = { bg = "surface1"}
"editor.border" = { bg = "base", fg = "text" }
"editor.pane_border" = { bg = "base", fg = "crust" }
"editor.ruler" = { fg = "surface0" }
"editor.error_text" = { fg = "red" }
"editor.search.match" = { bg = "search_match" }
"editor.fuzzy.match" = { fg = "red" }
"editor.completer" = { bg = "surface1", fg = "text" }
"editor.completer.selected" = { bg = "blue", fg = "surface0" }
"editor.cursorline" = { bg = "cursorline" }
"editor.scrollbar" = { bg = "mantle", fg = "scrollbar" }
"editor.file_explorer.directory" = { fg = "blue" }
"editor.file_explorer.executable" = { fg = "green" }
"editor.file_explorer.link" = { fg = "teal" }
"editor.conflict.current" = { bg = "conflict-current" }
"editor.conflict.incoming" = { bg = "conflict-incoming" }

[syntax]
"type" = { fg = "yellow" }

"constructor" = { fg = "sapphire" }

"constant" = { fg = "peach" }
"constant.builtin" = { fg = "peach" }
"constant.character" = { fg = "teal" }
"constant.character.escape" = { fg = "pink"}

"string" = { fg = "green" }
"string.regexp" = { fg = "peach" }
"string.special" = { fg = "blue" }

"comment" = { fg = "surface2" }
"info" = { fg = "yellow" }
"hint" = { fg = "yellow" }

"variable" = { fg = "text" }
"variable.parameter" = { fg = "maroon" }
"variable.builtin" = { fg = "red" }
"variable.other.member" = { fg = "teal" }

"label" = { fg = "sapphire" }

"punctuation" = { fg = "overlay2" }
"punctuation.special" = { fg = "sky" }

"keyword" = { fg = "mauve" }
"key" = { fg = "teal" }

"operator" = { fg = "sky" }

"function" = { fg = "blue" }
"function.builtin" = { fg = "peach" }
"function.macro" = { fg = "mauve" }

"tag" = { fg = "mauve" }

"namespace" = { fg = "blue" }

"special" = { fg = "blue" }

"attribute" = { fg = "blue" }

"diff.plus" = { fg = "green" }
"diff.minus" = { fg = "red" }
"diff.delta" = { fg = "blue" }

# Special case for languages
"rust.type.builtin" = { fg = "yellow" }

"markup.heading" = { fg = "lavender" }
"markup.raw" = { fg = "flamingo" }
"markup.bold" = { fg = "text" }
"markup.italic" = { fg = "teal" }
"markup.list" = { fg = "mauve" }
"markup.quote" = { fg = "yellow" }
"markup.link.url" = { fg = "rosewater" }
"markup.link.text" = { fg = "blue" }

[palette]
rosewater = "#f4dbd6"
flamingo = "#f0c6c6"
pink = "#f5bde6"
mauve = "#c6a0f6"
red = "#ed8796"
maroon = "#ee99a0"
peach = "#f5a97f"
yellow = "#eed49f"
green = "#a6da95"
teal = "#8bd5ca"
sky = "#91d7e3"
sapphire = "#7dc4e4"
blue = "#8aadf4"
lavender = "#b7bdf8"

text = "#cad3f5"
subtext1 = "#b8c0e0"
subtext0 = "#a5adcb"
overlay2 = "#939ab7"
overlay1 = "#8087a2"
overlay0 = "#6e738d"
surface2 = "#5b6078"
surface1 = "#494d64"
surface0 = "#363a4f"

base = "#24273a"
mantle = "#1e2030"
crust = "#181926"

search_match = "#4a5b6b"
cursorline = "#303347"
scrollbar = "#3d4054"

conflict-current  = "#27403B"
conflict-incoming = "#28384B"