
"editor.line_nr" = { fg = "fg4", bg = "bg0" }
"editor.current_line_nr" = { fg = "fg1", bg = "bg0" }
"editor.text" = { fg = "fg1" }
"editor.dim_text" = { fg = "ruler" }
"editor.info_line" = { fg = "fg2", bg = "bg1" }
"editor.info_line.unfocused" = { fg = "fg4", bg = "bg1" }
"editor.background" = { bg = "bg0", fg = "fg1" }
"editor.selection" = { bg = "bg3"}
"editor.border" = { fg = "fg1", bg = "bg0" }
"editor.pane_border" = { fg = "fg1", bg = "bg0" }
"editor.ruler" = { fg = "ruler" }
"editor.error_text" = { fg = "red1" }
"editor.search.match" = { bg = "search_match" }
"editor.fuzzy.match" = { fg = "red1" }
"editor.completer" = { bg = "bg3", fg = "fg1" }
"editor.completer.selected" = { bg = "blue1", fg = "bg0" }
"editor.cursorline" = { bg = "bg1" }
"editor.scrollbar" = { bg = "bg0", fg = "scrollbar" }
"editor.file_explorer.directory" = { fg = "blue0" }
"editor.file_explorer.executable" = { fg = "green0" }
"editor.file_explorer.link" = { fg = "aqua0" }
"editor.conflict.current" = { bg = "conflict-current" }
"editor.conflict.incoming" = { bg = "conflict-incoming" }

[syntax]
"tag" = { fg = "red1" }
"attribute" = { fg = "orange1" }

"warning" = { fg = "yellow0" }
"error" = { fg = "red1" }

"comment" = { fg = "gray1" }
"info" = { fg = "yellow0" }
"hint" = { fg = "yellow0" }

"constant" = { fg = "orange1" }
"constant.numeric" = { fg = "orange1" }
"constant.builtin" = { fg = "orange1" }
"constant.character.escape" = { fg = "aqua1" }

"escape" = { fg = "aqua1" }
"function" = { fg = "blue1" }
"key" = { fg = "red1" }

"keyword" = { fg = "purple1" }

"label" = { fg = "yellow1" }
"namespace" = { fg = "fg1" }
"operator" = { fg = "purple1" }
"special" = { fg = "orange1" }
"string" = { fg = "green1" }
"type" = { fg = "aqua1" }
"type.enum.variant" = { fg = "blue1" }
"type.builtin" = { fg = "purple1" }

"variable" = { fg = "fg1" }
"variable.other.member" = { fg = "red1" }
"variable.parameter" = { fg = "red1" }

"constructor" = { fg = "blue1" }
"property" = { fg = "fg1" }
"punctuation.bracket" = { fg = "fg1" }
"punctuation.delimiter" = { fg = "fg1" }
"punctuation.bracket.closure" = { fg = "purple1" }

"markup.heading" = { fg = "red1" }
"markup.raw.inline" = { fg = "green1" }
"markup.bold" = { fg = "orange1" }
"markup.italic" = { fg = "purple1" }
"markup.list" = { fg = "red1" }
"markup.quote" = { fg = "yellow1" }
"markup.link.url" = { fg = "aqua1" }
"markup.link.text" = { fg = "purple1" }

"diff.plus" = { fg = "green1" }
"diff.delta" = { fg = "orange1" }
"diff.minus" = { fg = "red1" }

# Special case for languages
"type.builtin.rust" = { fg = "yellow1" }

[palette]
bg0 = "#282828" # main background
bg1 = "#3c3836"
bg2 = "#504945"
bg3 = "#665c54"
bg4 = "#7c6f64"

fg0 = "#fbf1c7"
fg1 = "#ebdbb2" # main foreground
fg2 = "#d5c4a1"
fg3 = "#bdae93"
fg4 = "#a89984" # gray0

gray0 = "#a89984"
gray1 = "#928374"

red0 = "#cc241d" # neutral
red1 = "#fb4934" # bright
green0 = "#98971a"
green1 = "#b8bb26"
yellow0 = "#d79921"
yellow1 = "#fabd2f"
blue0 = "#458588"
blue1 = "#83a598"
purple0 = "#b16286"
purple1 = "#d3869b"
aqua0 = "#689d6a"
aqua1 = "#8ec07c"
orange0 = "#d65d0e"
orange1 = "#fe8019"

ruler = "#48443f"

search_match = "#503825"
scrollbar = "#403c39"

conflict-current  = "#27403B"
conflict-incoming = "#28384B"