
"editor.line_nr" = { fg = "line_nr", bg = "black" }
"editor.current_line_nr" = { fg = "white", bg = "black" }
"editor.text" = { fg = "white" }
"editor.dim_text" = { fg = "faint_gray" }
"editor.info_line" = { fg = "white", bg = "light_black" }
"editor.info_line.unfocused" = { fg = "line_nr", bg = "light_black" }
"editor.background" = { bg = "black", fg = "white" }
"editor.selection" = { bg = "gray"}
"editor.border" = { bg = "black", fg = "white" }
"editor.pane_border" = { bg = "black", fg = "gray" }
"editor.ruler" = { fg = "faint_gray" }
"editor.error_text" = { fg = "red" }
"editor.search.match" = { bg = "faint_blue" }
"editor.fuzzy.match" = { fg = "red" }
"editor.completer" = { bg = "gray", fg = "white" }
"editor.completer.selected" = { bg = "blue", fg = "black" }
"editor.cursorline" = { bg = "cursorline" }
"editor.scrollbar" = { bg = "black", fg = "scrollbar" }
"editor.file_explorer.directory" = { fg = "blue" }
"editor.file_explorer.executable" = { fg = "green" }
"editor.file_explorer.link" = { fg = "cyan" }
"editor.conflict.current" = { bg = "conflict-current" }
"editor.conflict.incoming" = { bg = "conflict-incoming" }

[syntax]
"tag" = { fg = "red" }
"attribute" = { fg = "gold" }

"warning" = { fg = "yellow" }
"error" = { fg = "red" }

"comment" = { fg = "light_gray" }
"info" = { fg = "yellow" }
"hint" = { fg = "yellow" }

"constant" = { fg = "gold" }
"constant.numeric" = { fg = "gold" }
"constant.builtin" = { fg = "gold" }
"constant.character.escape" = { fg = "cyan" }

"escape" = { fg = "cyan" }
"function" = { fg = "blue" }
"key" = { fg = "red" }

"keyword" = { fg = "purple" }

"label" = { fg = "yellow" }
"namespace" = { fg = "white" }
"operator" = { fg = "purple" }
"special" = { fg = "gold" }
"string" = { fg = "green" }
"type" = { fg = "cyan" }
"type.enum.variant" = { fg = "blue" }
"type.builtin" = { fg = "purple" }

"variable" = { fg = "red" }

"constructor" = { fg = "blue" }
"property" = { fg = "white" }
"punctuation.bracket" = { fg = "white" }
"punctuation.delimiter" = { fg = "white" }
"punctuation.bracket.closure" = { fg = "purple" }

"markup.heading" = { fg = "red" }
"markup.raw.inline" = { fg = "green" }
"markup.bold" = { fg = "gold" }
"markup.italic" = { fg = "purple" }
"markup.list" = { fg = "red" }
"markup.quote" = { fg = "yellow" }
"markup.link.url" = { fg = "cyan" }
"markup.link.text" = { fg = "purple" }

"diff.plus" = { fg = "green" }
"diff.delta" = { fg = "gold" }
"diff.minus" = { fg = "red" }

# Special case for languages
"type.builtin.rust" = { fg = "yellow" }

[palette]
yellow = "#e5c07b"
blue = "#61afef"
red = "#e06c75"
purple = "#c678dd"
green = "#98c379"
gold = "#d19a66"
cyan = "#56b6c2"
white = "#abb2bf"
black = "#282c34"
light_black = "#2c323c"
gray = "#3e4452"
faint_gray = "#3b4048"
light_gray = "#5c6370"
line_nr = "#4b5263"
faint_blue = "#324971"

cursorline = "#2c313c"
scrollbar = "#3b414d"

conflict-current  = "#27403B"
conflict-incoming = "#28384B"